name: leo_confecciones
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  # UI y estilos
  cupertino_icons: ^1.0.8
  
  # Manejo de estado
  provider: ^6.1.5+1
  
  # Navegación
  go_router: ^14.2.0
  
  # Almacenamiento local
  shared_preferences: ^2.3.2
  
  # Formateo de fechas y números
  intl: ^0.19.0
  
  # Generación de PDF
  pdf: ^3.10.8
  
  # Impresión y compartición
  printing: ^5.11.1
  
  # Formularios avanzados
  flutter_form_builder: ^9.2.1
  
  # Selector de fechas
  flutter_datetime_picker_plus: ^2.1.0
  
  # Íconos adicionales
  font_awesome_flutter: ^10.7.0
  
  # BASE DE DATOS LOCAL
  sqflite: ^2.3.0
  path_provider: ^2.1.0
  path: ^1.9.0
  
  # COMPARTIR ARCHIVOS
  share_plus: ^10.0.0

  # ========== FIREBASE ==========
  firebase_core: ^3.3.0
  cloud_firestore: ^5.4.0
  firebase_auth: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true